apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-kuma-pvc
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
