apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-kuma-pvc
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
